
<div class="container">
    <div id="carrusel">
      <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">  
                    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                      <div class="carousel-inner">
                       
                        <div class="carousel-item active">
                          <img  class="d-block w-100" src="web/imagenes/carrusel/playa-noja1.jpg" alt="First slide">
                        </div>

                        <div class="carousel-item">
                            <img class="d-block w-100" src="web/imagenes/carrusel/playa-castro1.jpg" alt="First slide">
                        </div>

                        <div class="carousel-item">
                          <img class="d-block w-100" src="web/imagenes/carrusel/playa-zarautz1.jpg" alt="Zarautz slide">
                        </div>
                     
                        <div class="carousel-item">
                          <img class="d-block w-100" src="web/imagenes/carrusel/playa-sanjuandeluz.jpg" alt="Fourd slide">
                        </div>

                        <div class="carousel-item">
                          <img class="d-block w-100" src="web/imagenes/carrusel/playa-laredo2.jpg" alt="Second slide">
                        </div>
                        
                        <div class="carousel-item">
                          <img class="d-block w-100" src="web/imagenes/carrusel/zarautz_carrusel.jpg" alt="Zarautz slide">
                        </div>

                    <!-- <img class="d-block w-100" src="web/imagenes/Somo.jpg" alt="Third slide">-->
                    <!--
                        <div class="carousel-item active">
                              <picture>
                                <source media="(max-width:2100px)"srcset="web/imagenes/playa-noja1.jpg">
                                <source media="(max-width:650px)" srcset="web/imagenes/zarautz_carrusel.jpg">
                                <source media="(max-width:465px)" srcset="web/imagenes/Somo.jpg">
                                <img src="web/imagenes/fuenterrabia.jpg" alt="Flowers">
                              </picture>
                        </div>
                      -->
                    </div>
                  </div>
          </div>
      </div>
    </div>
</div>